/*----- PROTECTED REGION ID(SFinderStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        SFinderStateMachine.cpp
//
// description : State machine file for the SFinder class
//
// project :     Source finder worker
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <SFinder.h>

/*----- PROTECTED REGION END -----*/	//	SFinder::SFinderStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  INIT     |  Initializing state: used when reserved of under configuration options
//  ON       |  Default state when server is free of tasks (e.g. it can be reserved)
//  FAULT    |  Fault state, e.g. when internal error occurred or when task failed
//  RUNNING  |  State activated when a task is started


namespace SFinder_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_useLocalBkg_allowed()
 *	Description : Execution allowed for useLocalBkg attribute
 */
//--------------------------------------------------------
bool SFinder::is_useLocalBkg_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for useLocalBkg attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::useLocalBkgStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::useLocalBkgStateAllowed_WRITE

	//	Not any excluded states for useLocalBkg attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::useLocalBkgStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::useLocalBkgStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_use2ndPassInLocalBkg_allowed()
 *	Description : Execution allowed for use2ndPassInLocalBkg attribute
 */
//--------------------------------------------------------
bool SFinder::is_use2ndPassInLocalBkg_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for use2ndPassInLocalBkg attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::use2ndPassInLocalBkgStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::use2ndPassInLocalBkgStateAllowed_WRITE

	//	Not any excluded states for use2ndPassInLocalBkg attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::use2ndPassInLocalBkgStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::use2ndPassInLocalBkgStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_skipNegativePixels_allowed()
 *	Description : Execution allowed for skipNegativePixels attribute
 */
//--------------------------------------------------------
bool SFinder::is_skipNegativePixels_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for skipNegativePixels attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::skipNegativePixelsStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::skipNegativePixelsStateAllowed_WRITE

	//	Not any excluded states for skipNegativePixels attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::skipNegativePixelsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::skipNegativePixelsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_skipOutliersInLocalBkg_allowed()
 *	Description : Execution allowed for skipOutliersInLocalBkg attribute
 */
//--------------------------------------------------------
bool SFinder::is_skipOutliersInLocalBkg_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for skipOutliersInLocalBkg attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::skipOutliersInLocalBkgStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::skipOutliersInLocalBkgStateAllowed_WRITE

	//	Not any excluded states for skipOutliersInLocalBkg attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::skipOutliersInLocalBkgStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::skipOutliersInLocalBkgStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_localBkgMethod_allowed()
 *	Description : Execution allowed for localBkgMethod attribute
 */
//--------------------------------------------------------
bool SFinder::is_localBkgMethod_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for localBkgMethod attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::localBkgMethodStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgMethodStateAllowed_WRITE

	//	Not any excluded states for localBkgMethod attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::localBkgMethodStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgMethodStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_bkgEstimator_allowed()
 *	Description : Execution allowed for bkgEstimator attribute
 */
//--------------------------------------------------------
bool SFinder::is_bkgEstimator_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for bkgEstimator attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::bkgEstimatorStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::bkgEstimatorStateAllowed_WRITE

	//	Not any excluded states for bkgEstimator attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::bkgEstimatorStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::bkgEstimatorStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_useBeamInfoInBkg_allowed()
 *	Description : Execution allowed for useBeamInfoInBkg attribute
 */
//--------------------------------------------------------
bool SFinder::is_useBeamInfoInBkg_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for useBeamInfoInBkg attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::useBeamInfoInBkgStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::useBeamInfoInBkgStateAllowed_WRITE

	//	Not any excluded states for useBeamInfoInBkg attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::useBeamInfoInBkgStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::useBeamInfoInBkgStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_localBkgBoxSizeX_allowed()
 *	Description : Execution allowed for localBkgBoxSizeX attribute
 */
//--------------------------------------------------------
bool SFinder::is_localBkgBoxSizeX_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for localBkgBoxSizeX attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::localBkgBoxSizeXStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgBoxSizeXStateAllowed_WRITE

	//	Not any excluded states for localBkgBoxSizeX attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::localBkgBoxSizeXStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgBoxSizeXStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_localBkgBoxSizeY_allowed()
 *	Description : Execution allowed for localBkgBoxSizeY attribute
 */
//--------------------------------------------------------
bool SFinder::is_localBkgBoxSizeY_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for localBkgBoxSizeY attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::localBkgBoxSizeYStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgBoxSizeYStateAllowed_WRITE

	//	Not any excluded states for localBkgBoxSizeY attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::localBkgBoxSizeYStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgBoxSizeYStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_localBkgGridStepSizeX_allowed()
 *	Description : Execution allowed for localBkgGridStepSizeX attribute
 */
//--------------------------------------------------------
bool SFinder::is_localBkgGridStepSizeX_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for localBkgGridStepSizeX attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::localBkgGridStepSizeXStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgGridStepSizeXStateAllowed_WRITE

	//	Not any excluded states for localBkgGridStepSizeX attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::localBkgGridStepSizeXStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgGridStepSizeXStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_localBkgGridStepSizeY_allowed()
 *	Description : Execution allowed for localBkgGridStepSizeY attribute
 */
//--------------------------------------------------------
bool SFinder::is_localBkgGridStepSizeY_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for localBkgGridStepSizeY attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::localBkgGridStepSizeYStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgGridStepSizeYStateAllowed_WRITE

	//	Not any excluded states for localBkgGridStepSizeY attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::localBkgGridStepSizeYStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::localBkgGridStepSizeYStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_seedThr_allowed()
 *	Description : Execution allowed for seedThr attribute
 */
//--------------------------------------------------------
bool SFinder::is_seedThr_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for seedThr attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::seedThrStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::seedThrStateAllowed_WRITE

	//	Not any excluded states for seedThr attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::seedThrStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::seedThrStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_mergeThr_allowed()
 *	Description : Execution allowed for mergeThr attribute
 */
//--------------------------------------------------------
bool SFinder::is_mergeThr_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for mergeThr attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::mergeThrStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::mergeThrStateAllowed_WRITE

	//	Not any excluded states for mergeThr attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::mergeThrStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::mergeThrStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_minNPix_allowed()
 *	Description : Execution allowed for minNPix attribute
 */
//--------------------------------------------------------
bool SFinder::is_minNPix_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for minNPix attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::minNPixStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::minNPixStateAllowed_WRITE

	//	Not any excluded states for minNPix attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::minNPixStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::minNPixStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_mergeBelowSeed_allowed()
 *	Description : Execution allowed for mergeBelowSeed attribute
 */
//--------------------------------------------------------
bool SFinder::is_mergeBelowSeed_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for mergeBelowSeed attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::mergeBelowSeedStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::mergeBelowSeedStateAllowed_WRITE

	//	Not any excluded states for mergeBelowSeed attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::mergeBelowSeedStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::mergeBelowSeedStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_searchNegativeExcess_allowed()
 *	Description : Execution allowed for searchNegativeExcess attribute
 */
//--------------------------------------------------------
bool SFinder::is_searchNegativeExcess_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for searchNegativeExcess attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::searchNegativeExcessStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::searchNegativeExcessStateAllowed_WRITE

	//	Not any excluded states for searchNegativeExcess attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::searchNegativeExcessStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::searchNegativeExcessStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_nestedBlobThrFactor_allowed()
 *	Description : Execution allowed for nestedBlobThrFactor attribute
 */
//--------------------------------------------------------
bool SFinder::is_nestedBlobThrFactor_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for nestedBlobThrFactor attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::nestedBlobThrFactorStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::nestedBlobThrFactorStateAllowed_WRITE

	//	Not any excluded states for nestedBlobThrFactor attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::nestedBlobThrFactorStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::nestedBlobThrFactorStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_searchCompactSources_allowed()
 *	Description : Execution allowed for searchCompactSources attribute
 */
//--------------------------------------------------------
bool SFinder::is_searchCompactSources_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for searchCompactSources attribute in Write access.
	/*----- PROTECTED REGION ID(SFinder::searchCompactSourcesStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::searchCompactSourcesStateAllowed_WRITE

	//	Not any excluded states for searchCompactSources attribute in read access.
	/*----- PROTECTED REGION ID(SFinder::searchCompactSourcesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::searchCompactSourcesStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SFinder::is_ExtractSources_allowed()
 *	Description : Execution allowed for ExtractSources attribute
 */
//--------------------------------------------------------
bool SFinder::is_ExtractSources_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(SFinder::ExtractSourcesStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SFinder::ExtractSourcesStateAllowed
		return false;
	}
	return true;
}


/*----- PROTECTED REGION ID(SFinder::SFinderStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	SFinder::SFinderStateAllowed.AdditionalMethods

}	//	End of namespace
